databases:
  - name: budget_app
    ipAllowList: []
    databaseName: budget_app
    user: budget_app

services:
  - type: web
    name: rails
    env: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budget_app
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
  # - type: redis
  #   name: redis
  #   ipAllowList: []
  #   plan: free
  #   maxmemoryPolicy: noeviction